const EXPRESS_CONFIGURATION = {
    EXPRESS_DEFAULT_PORT: 8080,
    EXPRESS_PRODUCTS_BASE_ROUTE: '/api/products',
    EXPRESS_CARTS_BASE_ROUTE: '/api/carts',
    EXPRESS_HANDLEBARS_BASE_ROUTE: '/'
}


export {
    EXPRESS_CONFIGURATION as default
} 