
const MONGOOSE_PREV_KEY_NAME = 'mongoose';
const MONGOOSE_CONFIGURATION_URL_KEY = `${MONGOOSE_PREV_KEY_NAME}_url`;
const MONGOOSE_CONFIGURATION_PORT_KEY = `${MONGOOSE_PREV_KEY_NAME}_port`;
const MONGOOSE_CONFIGURATION_DB_KEY = `${MONGOOSE_PREV_KEY_NAME}_db`;
const MONGOOSE_CONFIGURATION_COLLECTIONS_KEY = `${MONGOOSE_PREV_KEY_NAME}_collection`;

export {
    MONGOOSE_PREV_KEY_NAME,
    MONGOOSE_CONFIGURATION_PORT_KEY,
    MONGOOSE_CONFIGURATION_URL_KEY,
    MONGOOSE_CONFIGURATION_DB_KEY,
    MONGOOSE_CONFIGURATION_COLLECTIONS_KEY,
};