const OAUTH_PREV_ENV_KEY = 'OAUTH_';
const OAUTH_GITHUB_ENV_KEY = `${OAUTH_PREV_ENV_KEY}GITHUB_`;

const GITHUB_CLIENT_ID_ENV_KEY = `${OAUTH_GITHUB_ENV_KEY}CLIENT_ID`;
const GITHUB_CLIENT_SECRET_ENV_KEY = `${OAUTH_GITHUB_ENV_KEY}CLIENT_SECRET`;
const GITHUB_CALLBACK_ENV_KEY = `${OAUTH_GITHUB_ENV_KEY}CALLBACK`;


export {
    GITHUB_CLIENT_ID_ENV_KEY,
    GITHUB_CLIENT_SECRET_ENV_KEY,
    GITHUB_CALLBACK_ENV_KEY
};